USE ECOMMERCE_DB;

-- Total orders
SELECT COUNT(ORDER_ID) AS Total_orders FROM ORDERS;

-- Active users
SELECT COUNT(DISTINCT USER_ID) AS Active_users FROM EVENTS;

-- Total revenue
SELECT ROUND(SUM(TOTAL_AMOUNT),0) AS Total_revenue FROM ORDERS;

-- Average order value
SELECT ROUND(AVG(TOTAL_AMOUNT),0) AS Average_order_value FROM ORDERS;

-- Average rating
SELECT ROUND(AVG(RATING),1) AS Average_rating FROM REVIEWS;

-- Total orders based on per month
SELECT MONTH,COUNT(ORDER_ID)AS TOTAL_ORDERS
FROM ORDERS
GROUP BY MONTH,MONTH_NUM
ORDER BY MONTH_NUM;
  
-- Total revenue by product category
SELECT CATEGORY,ROUND(SUM(ITEM_TOTAL),0) AS TOTAL_REVENUE FROM PRODUCTS
LEFT JOIN ORDER_ITEMS
ON PRODUCTS.PRODUCT_ID=ORDER_ITEMS.PRODUCT_ID
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE DESC;

-- Distribution of orders based on order_status
SELECT ORDER_STATUS,COUNT(ORDER_ID) AS ORDERS_DISTRIBUTION FROM ORDERS
GROUP BY ORDER_STATUS;

-- Total orders based on product category
SELECT CATEGORY,COUNT(ORDER_ID) AS TOTAL_ORDERS FROM PRODUCTS
LEFT JOIN ORDER_ITEMS
ON PRODUCTS.PRODUCT_ID=ORDER_ITEMS.PRODUCT_ID
GROUP BY CATEGORY
ORDER BY TOTAL_ORDERS DESC;

-- Average rating on Brand
SELECT BRAND,ROUND(AVG(RATING),1) AS Average_rating FROM PRODUCTS
GROUP BY BRAND
ORDER BY Average_rating DESC;

-- Quantity sold per Category
SELECT CATEGORY,SUM(QUANTITY) AS QUANTITY_SOLD FROM PRODUCTS
LEFT JOIN ORDER_ITEMS
ON PRODUCTS.PRODUCT_ID=ORDER_ITEMS.PRODUCT_ID
GROUP BY CATEGORY
ORDER BY QUANTITY_SOLD DESC; 

-- Top 10 products based on orders
SELECT PRODUCT_NAME,COUNT(ORDER_ID) AS Total_orders FROM PRODUCTS
LEFT JOIN ORDER_ITEMS
ON PRODUCTS.PRODUCT_ID=ORDER_ITEMS.PRODUCT_ID
GROUP BY PRODUCT_NAME
ORDER BY Total_orders DESC 
LIMIT 10;

-- Top 10 products by revenue
SELECT PRODUCT_NAME, ROUND(SUM(ITEM_TOTAL),0) AS Total_revenue FROM PRODUCTS
LEFT JOIN ORDER_ITEMS
ON PRODUCTS.PRODUCT_ID=ORDER_ITEMS.PRODUCT_ID
GROUP BY PRODUCT_NAME
ORDER BY Total_revenue DESC
LIMIT 10;

-- Users activity analysis
SELECT EVENT_TYPE,COUNT(USER_ID) AS Total_activity FROM EVENTS
GROUP BY EVENT_TYPE
ORDER BY Total_activity Desc;

-- Total users percentage by gender
SELECT GENDER,CONCAT(ROUND((COUNT(USER_ID)/(SELECT COUNT(USER_ID) FROM USERS))*100,0),'%') AS USERS_PERCENTAGE FROM USERS
GROUP BY GENDER
ORDER BY USERS_PERCENTAGE DESC; 

-- Top 5 city with high number of users
SELECT DISTINCT CITY,COUNT(USER_ID) AS Total_users FROM USERS
GROUP BY CITY
ORDER BY Total_users desc
LIMIT 5;

-- Top 5 city with low number of users
SELECT DISTINCT CITY,COUNT(USER_ID) AS TOTAL_USERS FROM USERS
GROUP BY CITY
ORDER BY TOTAL_USERS ASC
LIMIT 5;
 





